import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve, join } from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const vault = resolve(process.env.OBSIDIAN_VAULT || "../Obsidian-dashell-player-Dev");
if (!prod && process.env.OBSIDIAN_VAULT && !existsSync(join(vault, ".obsidian"))) {
	throw new Error(`Obsidian vault not found: ${vault}`);
}
const syncToVault = !prod && existsSync(join(vault, ".obsidian"));

const assetsPlugin = {
	name: "obsidian-assets",
	setup(build) {
		// Include standalone styles and metadata in esbuild's watch graph.
		build.onLoad({ filter: /[\\/]src[\\/]main\.ts$/ }, async (args) => ({
			contents: await readFile(args.path, "utf8"),
			loader: "ts",
			watchFiles: [resolve("styles-base.css"), resolve("manifest.json")],
		}));
		build.onEnd(async (result) => {
			if (result.errors.length) return;
			const base = await readFile("styles-base.css", "utf8");
			const compiled = existsSync("main.css") ? await readFile("main.css", "utf8") : "";
			await writeFile("styles.css", base + "\n\n/* === Additional Compiled Styles === */\n" + compiled);
			if (!syncToVault) return;
			const manifest = JSON.parse(await readFile("manifest.json", "utf8"));
			const target = join(vault, ".obsidian", "plugins", manifest.id);
			await mkdir(target, { recursive: true });
			await writeFile(join(target, ".hotreload"), "");
			for (const file of ["manifest.json", "styles.css", "main.js"]) {
				await copyFile(file, join(target, file));
			}
			console.log(`[dev] Synced to ${target}`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	loader: {
		".tsx": "tsx",
		".ts": "ts",
		".css": "css",
		".jpg": "dataurl",
	},
	bundle: true,
	jsx: "automatic",
	jsxImportSource: "react",
	plugins: [assetsPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	console.log(syncToVault
		? `[dev] Watching source, styles and manifest. Target vault: ${vault}`
		: "[dev] Watching locally. Set OBSIDIAN_VAULT to sync to an Obsidian vault.");
	await context.watch();
}
