import type { MediaSource } from '../types';

/**
 * A local media resource URL is regenerated by Obsidian after a restart, so it
 * cannot identify a persisted association. Vault paths are stable across a
 * player reload; remote media keeps its normalized URL as the identity.
 */
export function buildSubtitleAssociationKey(source: Pick<MediaSource, 'type' | 'url' | 'file'>): string {
  if (source.type === 'local' && source.file?.path) {
    return `file:${source.file.path}`;
  }
  const url = source.url.trim();
  return url ? `url:${url}` : '';
}

/** Keep only usable string pairs when reading persisted plugin data. */
export function normalizeSubtitleAssociations(value: unknown): Record<string, string> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return {};

  const associations: Record<string, string> = {};
  for (const [rawKey, rawPath] of Object.entries(value)) {
    const key = rawKey.trim();
    const path = typeof rawPath === 'string' ? rawPath.trim().replace(/\\/g, '/') : '';
    if (!key || !path) continue;
    associations[key] = path;
  }
  return associations;
}

export function updateSubtitleAssociationsForRename(
  associations: Record<string, string>,
  oldPath: string,
  newPath: string,
  renamedFileIsSubtitle: boolean,
): Record<string, string> {
  const updatePath = (path: string): string =>
    path === oldPath ? newPath : path.startsWith(`${oldPath}/`) ? `${newPath}${path.slice(oldPath.length)}` : path;
  const next: Record<string, string> = {};

  for (const [key, subtitlePath] of Object.entries(associations)) {
    const nextKey = key.startsWith('file:')
      ? `file:${updatePath(key.slice('file:'.length))}`
      : key;
    const nextSubtitlePath = renamedFileIsSubtitle ? updatePath(subtitlePath) : subtitlePath;
    next[nextKey] = nextSubtitlePath;
  }
  return next;
}

export function removeSubtitleAssociationsForDeletedFile(
  associations: Record<string, string>,
  deletedPath: string,
  deletedFileIsSubtitle: boolean,
): Record<string, string> {
  const hasDeletedPath = (path: string): boolean =>
    path === deletedPath || path.startsWith(`${deletedPath}/`);
  const next: Record<string, string> = {};

  for (const [key, subtitlePath] of Object.entries(associations)) {
    if (key.startsWith('file:') && hasDeletedPath(key.slice('file:'.length))) continue;
    if (deletedFileIsSubtitle && hasDeletedPath(subtitlePath)) continue;
    next[key] = subtitlePath;
  }
  return next;
}

export function subtitleAssociationsEqual(
  left: Record<string, string>,
  right: Record<string, string>,
): boolean {
  const leftKeys = Object.keys(left);
  if (leftKeys.length !== Object.keys(right).length) return false;
  return leftKeys.every((key) => left[key] === right[key]);
}
